Ifrit/Controllers/EmployerController.cs
using AutoMapper;
using Ifrit.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Ifrit.Controllers
{
    public class EmployerController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        //Метод определения текущего пользователя
        private async Task<ApplicationUser> GetCurrentUser()
        {
            ApplicationUser user = new ApplicationUser();
            string userId = User.Identity.GetUserId();
            return await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
        }
        // GET
        public async Task<ActionResult> GetBusinessCard()
        {
            ApplicationUser user = await GetCurrentUser();
            UIBusinessCard UserBusinessCard = new UIBusinessCard();            
            var DBUserBusinessCard = user.BusinessCard;
            if (DBUserBusinessCard != null)
            {
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<BusinessCard, UIBusinessCard>());
                //сопоставление
                UserBusinessCard = Mapper.Map<BusinessCard, UIBusinessCard>(DBUserBusinessCard);
                return View("ShowBusinessCard",UserBusinessCard);
            }
            else
            {
                return View();
            }
        }
        [HttpPost]
        public async Task<ActionResult> GetBusinessCard(UIBusinessCard UserBusinessCard, HttpPostedFileBase uploadImage)
        {
            ApplicationUser user = await GetCurrentUser();
            if (ModelState.IsValid)
            {
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<UIBusinessCard, BusinessCard>());
                //сопоставление
                BusinessCard DBUserBusinessCard = Mapper.Map<UIBusinessCard, BusinessCard>(UserBusinessCard);
                DBUserBusinessCard.User = user;
                byte[] imageData = null;
                // считываем переданный файл в массив байтов
                using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                {
                    imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                }
                // установка массива байтов
                DBUserBusinessCard.Logo = imageData;
                user.BusinessCard = DBUserBusinessCard;
                db.Users.Attach(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index","Vacancies");
            }
            return View();
        }
        public async Task<ActionResult> DeleteBusinessCard(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusinessCard DBUserBusinessCard = await db.BusinessCards.FindAsync(id);
            if (DBUserBusinessCard == null)
            {
                return HttpNotFound();
            }
            return View(DBUserBusinessCard);
        }
        [HttpPost, ActionName("DeleteBusinessCard")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            BusinessCard DBUserBusinessCard = await db.BusinessCards.FindAsync(id);
            db.BusinessCards.Remove(DBUserBusinessCard);
            await db.SaveChangesAsync();
            return RedirectToAction("GetBusinessCard");
        }
        public async Task<ActionResult> EditBusinessCard(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BusinessCard DBUserBusinessCard = await db.BusinessCards.FindAsync(id);
            if (DBUserBusinessCard == null)
            {
                return HttpNotFound();
            }
            //конфигурация маппера
            Mapper.Initialize(cfg => cfg.CreateMap<BusinessCard, UIBusinessCard>());
            //сопоставление
            UIBusinessCard UserBusinessCard = Mapper.Map<BusinessCard, UIBusinessCard>(DBUserBusinessCard);
            return View(UserBusinessCard);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> EditBusinessCard(UIBusinessCard UserBusinessCard, HttpPostedFileBase uploadImage)
        {
            if (ModelState.IsValid)
            {
                BusinessCard DBUserBusinessCard = await db.BusinessCards.FindAsync(UserBusinessCard.BusinessCardId);                             
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<UIBusinessCard, BusinessCard>().ForMember(d => d.Logo, (options) => options.Ignore()));
                //сопоставление
                Mapper.Map(UserBusinessCard, DBUserBusinessCard);
                ApplicationUser user = await GetCurrentUser();            
                DBUserBusinessCard.User = user;                
                if (uploadImage != null)
                {
                    byte[] imageData = null;
                    // считываем переданный файл в массив байтов
                    using (var binaryReader = new BinaryReader(uploadImage.InputStream))
                    {
                        imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
                    }
                    // установка массива байтов
                    DBUserBusinessCard.Logo = imageData;
                }
                db.Entry(DBUserBusinessCard).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("GetBusinessCard");
            }
            return View();
        }
    }
}

Ifrit/Controllers/ResumesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ifrit.Models;
using Microsoft.AspNet.Identity;
using AutoMapper;

namespace Ifrit.Controllers
{
    public class ResumesController : Controller
    {
        #region вспомогательные методы и свойства
        private ApplicationDbContext db = new ApplicationDbContext();
        //Метод определения текущего пользователя
        private async Task<ApplicationUser> GetCurrentUser()
        {
            ApplicationUser user = new ApplicationUser();
            string userId = User.Identity.GetUserId();
            return await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
        #region CRUD методы
        // GET: Resumes
        [Authorize(Roles = "applicant")]
        public async Task<ActionResult> Index()
        {
            ApplicationUser user = await GetCurrentUser();
            return View(user.Resumes.ToList());            
        }

        // GET: Resumes/Details/5
        [Authorize(Roles = "applicant, employer")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resume resume = await db.Resumes.FindAsync(id);
            if (resume == null)
            {
                return HttpNotFound();
            }
            return View(resume);
        }

        // GET: Resumes/Create
        [Authorize(Roles = "applicant")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Resumes/Create  
        [Authorize(Roles = "applicant")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(UIResume resume)
        {          
            ApplicationUser user = await GetCurrentUser();
            if (ModelState.IsValid)
            {
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<UIResume, Resume>());
                //сопоставление
                Resume DBResume = Mapper.Map<UIResume, Resume>(resume);             
                DBResume.User = user;
                user.Resumes.Add(DBResume);
                db.Users.Attach(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Resumes/Edit/5
        [Authorize(Roles = "applicant")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resume DBresume = await db.Resumes.FindAsync(id);
            if (DBresume == null)
            {
                return HttpNotFound();
            }
            //конфигурация маппера
            Mapper.Initialize(cfg => cfg.CreateMap<Resume, UIResume>());
            //сопоставление
            UIResume UIresume = Mapper.Map<Resume, UIResume>(DBresume);            
            return View(UIresume);
        }

        // POST: Resumes/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "applicant")]
        public async Task<ActionResult> Edit(UIResume UIresume)
        {
            //ApplicationUser user = await GetCurrentUser();
            if (ModelState.IsValid)
            {
                ApplicationUser user = await GetCurrentUser();
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<UIResume, Resume>());
                //сопоставление
                Resume DBresume = Mapper.Map<UIResume, Resume>(UIresume);                
                DBresume.User = user;
                db.Entry(DBresume).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();                      
        }

        // GET: Resumes/Delete/5
        [Authorize(Roles = "applicant")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Resume resume = await db.Resumes.FindAsync(id);
            if (resume == null)
            {
                return HttpNotFound();
            }
            return View(resume);
        }

        // POST: Resumes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "applicant")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Resume resume = await db.Resumes.FindAsync(id);
            db.Resumes.Remove(resume);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        #endregion
        #region поиск
        // GET:
        [Authorize(Roles = "employer")]
        public ActionResult Find()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> Find(UIFindResume find)
        {
            var allResume = db.Resumes.Where(r => r.Title.ToLower().Contains(find.Title.ToLower())); //регистронезависимый поиск 
            return View("FindResult",await allResume.ToListAsync());
        }
        #endregion        
    }
}

Ifrit/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>    
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Платформа поиска работы Ifrit", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">                
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Платформа поиска работы Ifrit. Вы неавторизованы.</p>
        </footer>
    </div>    
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Ifrit/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Имя приложения", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("О программе", "About", "Home")</li>
                    <li>@Html.ActionLink("Контакт", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Платформа поиска работы Ifrit. Вы авторизованы как администратор.</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Ifrit/Views/Shared/_LayoutApplicant.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Ваши резюме", "Index", "Resumes")</li>
                    <li>@Html.ActionLink("Поиск вакансий", "Find", "Vacancies")</li>
                    <li>@Html.ActionLink("Личный кабинет", "Settings", "Applicant")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Платформа поиска работы Ifrit. Вы авторизованы как соискатель.</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Ifrit/Views/Shared/_LayoutEmployer.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>                
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Управление вакансиями", "Index", "Vacancies")</li>
                    <li>@Html.ActionLink("Поиск работников", "Find", "Resumes")</li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Кабинет <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>@Html.ActionLink("Визитка", "GetBusinessCard", "Employer")</li>
                            <li>@Html.ActionLink("Отклики", "Find", "Resumes")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – Платформа поиска работы Ifrit. Вы авторизованы как работодатель.</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>