Ifrit/Controllers/InteractionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace Ifrit.Controllers
{
    public class InteractionController : Controller
    {
        // GET: Interaction
        public ActionResult Index()
        {
            return View();
        }
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> Invite()
        {
            return View();
        }
        public async Task<ActionResult> Respond()
        {
            return View();
        }
    }
}

Ifrit/Controllers/VacanciesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ifrit.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using AutoMapper;

namespace Ifrit.Controllers
{
    public class VacanciesController : Controller
    {
        #region вспомогательные методы и свойства        
        private ApplicationDbContext db = new ApplicationDbContext();
        //Метод определения текущего пользователя
        private async Task<ApplicationUser> GetCurrentUser()
        {
            ApplicationUser user = new ApplicationUser();
            string userId = User.Identity.GetUserId();            
            return await db.Users.FirstOrDefaultAsync(u => u.Id == userId);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        #endregion
        #region CRUD методы
        // GET: Vacancies
        [Authorize(Roles = "employer")]
        public async Task<ActionResult>Index()
        {
            var user = await GetCurrentUser();
            return View(user.Vacancies.ToList());
        }

        // GET: Vacancies/Details/5
        [Authorize(Roles = "applicant, employer")]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy vacancy = await db.Vacancies.FindAsync(id);
            if (vacancy == null)
            {
                return HttpNotFound();
            }
            return View(vacancy);
        }

        // GET: Vacancies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Vacancies/Create       
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> Create(UIVacancy vacancy)
        {
            ApplicationUser user = await GetCurrentUser();           
            if (ModelState.IsValid)
            {
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<UIVacancy, Vacancy>());
                //сопоставление
                Vacancy DBvacancy = Mapper.Map<UIVacancy, Vacancy>(vacancy);
                DBvacancy.User = user;
                user.Vacancies.Add(DBvacancy);
                db.Users.Attach(user);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }          
            return View();   
        }

        // GET: Vacancies/Edit/5
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy DBvacancy = await db.Vacancies.FindAsync(id);
            if (DBvacancy == null)
            {
                return HttpNotFound();
            }
            //конфигурация маппера
            Mapper.Initialize(cfg => cfg.CreateMap<Vacancy, UIVacancy>());
            //сопоставление
            UIVacancy UIvacancy = Mapper.Map<Vacancy, UIVacancy>(DBvacancy);
            return View(UIvacancy);
        }

        // POST: Vacancies/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> Edit(UIVacancy UIvacancy)
        {
            if (ModelState.IsValid)
            {
                //конфигурация маппера
                Mapper.Initialize(cfg => cfg.CreateMap<UIVacancy, Vacancy>());
                //сопоставление
                Vacancy DBvacancy = Mapper.Map<UIVacancy, Vacancy>(UIvacancy);
                DBvacancy.User = await GetCurrentUser();
                db.Entry(DBvacancy).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View();
        }

        // GET: Vacancies/Delete/5
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Vacancy vacancy = await db.Vacancies.FindAsync(id);
            if (vacancy == null)
            {
                return HttpNotFound();
            }
            return View(vacancy);
        }

        // POST: Vacancies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "employer")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Vacancy vacancy = await db.Vacancies.FindAsync(id);
            db.Vacancies.Remove(vacancy);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        #endregion
        #region поиск
        // GET:
        [Authorize(Roles = "applicant")]
        public ActionResult Find()
        {
            return View();
        }
        [HttpPost]
        [Authorize(Roles = "applicant")]
        public async Task<ActionResult> Find(UIFindVacancy find)
        {
            var allVacancy = db.Vacancies.Where(r => r.Title.ToLower().Contains(find.Title.ToLower())); //делаю поиск регистронезависимым
            return View("FindResult", await allVacancy.ToListAsync());
        }
        #endregion  
    }
}

Ifrit/Views/Vacancies/Create.cshtml
@model Ifrit.Models.UIVacancy

@{
    ViewBag.Title = "Create";
}
<script src="~/Scripts/jquery-1.10.2.js"></script>
<script src="~/Scripts/jquery.validate.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<h2></h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Создание вакансии</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Название ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, "Содержание ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, "Заработная плата ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку вакансий", "Index")
</div>

Ifrit/Views/Vacancies/Delete.cshtml
@model Ifrit.Models.Vacancy

@{
    ViewBag.Title = "Delete";
}

<h2></h2>

<h3>Вы уверены?</h3>
<div>
    <h4>Удаление вакансии</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Body)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад к списку вакансий", "Index")
        </div>
    }
</div>

Ifrit/Views/Vacancies/Details.cshtml
@model Ifrit.Models.Vacancy

@{
    ViewBag.Title = "Details";
}

<h2></h2>

<div>
    <h4>Детали вакансии</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Название
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            Содержание
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Body)
        </dd>

        <dt>
            Заработная плата
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("employer"))
    {
        @Html.ActionLink("Редакстировать", "Edit", new { id = Model.VacancyId }) @:|
        @Html.ActionLink("Назад к списку вакансий", "Index");
    }
    @if (User.IsInRole("applicant"))
    {
        @Html.ActionLink("Откликнуться", "Respond", "Interaction", new { id = Model.VacancyId }) @:|
        @Html.ActionLink("Назад к поиску", "Find");
    }
</p>

Ifrit/Views/Vacancies/Edit.cshtml
@model Ifrit.Models.UIVacancy

@{
    ViewBag.Title = "Edit";
}

<h2></h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Редактирование</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VacancyId)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, "Название ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Body, "Содержание ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Body, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, "Заработная плата ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад к списку вакансий", "Index")
</div>

Ifrit/Views/Vacancies/Find.cshtml
@model Ifrit.Models.UIFindVacancy
@{
    ViewBag.Title = "Find";
}

<h2>Поиск резюме</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-group">
        @Html.LabelFor(model => model.Title, "Введите искомое резюме ", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
            @*@Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })*@
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Поиск..." class="btn btn-default" />
            </div>
        </div>
    </div>
}

Ifrit/Views/Vacancies/FindResult.cshtml
@model IEnumerable<Ifrit.Models.Vacancy>
@{
    ViewBag.Title = "FindResult";
}
<h2></h2>

@*<p>
        @Html.ActionLink("Создать новое", "Create")
    </p>*@
<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Содержание
        </th>
        <th>
            Заработная плата
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.VacancyId }) |
                @Html.ActionLink("Подробности", "Details", new { id = item.VacancyId }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.VacancyId })
            </td>
        </tr>
    }

</table>

Ifrit/Views/Vacancies/Index.cshtml
@model IEnumerable<Ifrit.Models.Vacancy>

@{
    ViewBag.Title = "Index";
}

<h2></h2>

<p>
    @Html.ActionLink("Добавить вакансию", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Название
        </th>
        <th>
            Содержание
        </th>
        <th>
            Заработная плата
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Body)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salary)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.VacancyId }) |
                @Html.ActionLink("Подробности", "Details", new { id = item.VacancyId }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.VacancyId })
            </td>
        </tr>
        
    }

</table>